---
- name: Download JDK package
  get_url:
    url:      "{{ oracle_java_jdk_url }}"
    dest:     /tmp/{{ oracle_java_jdk_url | basename }}
    mode:     0644
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie

- name: Download PyOpenSSL package
  get_url:
    url:  "{{ pyopenssl_url }}"
    dest: /tmp/{{ pyopenssl_url | basename}}
    mode: 0644

- name: Install PyOpenSSL package
  yum:
    name:   /tmp/{{ pyopenssl_url | basename}}
    state:  present

- name: Install JDK package
  yum:
    name:   /tmp/{{ oracle_java_jdk_url | basename }}
    state:  present

- name: Import Cloudera RPM repository GPG key
  rpm_key:
    key:    https://archive.cloudera.com/director/redhat/7/x86_64/director/RPM-GPG-KEY-cloudera
    state:  present
    
- name: Import Cloudera RPM repository
  yum_repository:
    name:         cloudera-director
    description:  Cloudera Director YUM repo
    baseurl:      http://archive.cloudera.com/director/redhat/7/x86_64/director/2/

- name: Install Cloudera Director
  yum:
    name:         cloudera-director-server
    state:        present
    update_cache: yes

- name: Create Cloudera Director configuration
  template:
    src:  application.properties.j2
    dest: /etc/cloudera-director-server/application.properties

- name: Create directory for SSL certificates
  file:
    path:   /etc/ssl/private
    state:  directory
    mode:   644

- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path:   /etc/letsencrypt/live/{{ director_public_dns }}
    state:  directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/letsencrypt/live/{{ director_public_dns }}/{{ director_public_dns }}.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path:             /etc/ssl/private/{{ director_public_dns }}.csr
    privatekey_path:  /etc/letsencrypt/live/{{ director_public_dns }}/{{ director_public_dns }}.key
    common_name:      "{{ director_public_dns }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path:             /etc/letsencrypt/live/{{ director_public_dns }}/{{ director_public_dns }}.crt
    privatekey_path:  /etc/letsencrypt/live/{{ director_public_dns }}/{{ director_public_dns }}.key
    csr_path:         /etc/ssl/private/{{ director_public_dns }}.csr
    provider:         selfsigned

- name: Create a key store for the given certificate.
  command: >
    keytool -genkeypair -alias director -keyalg RSA \
    -keystore /etc/ssl/private/{{ director_public_dns }}.jks \
    -keysize 4096 -dname "CN={{ director_public_dns }},O=cloudera.com,ST=CA,C=US" \
    -storepass {{ keystore_pass }} -keypass {{ keystore_pass }}
  register: createkeystore
  args:
    creates: /etc/ssl/private/{{ director_public_dns }}.jks

- name: Import SSL certificate to a given cacerts keystore
  java_cert:
    cert_path:      /etc/letsencrypt/live/{{ director_public_dns }}/{{ director_public_dns }}.crt
    cert_alias:     "{{ director_public_dns }}"
    keystore_path:  /etc/ssl/private/{{ director_public_dns }}.jks
    keystore_pass:  "{{ keystore_pass }}"
    state:          present
    
- name: Start Cloudera Director service.
  systemd:
    name:     cloudera-director-server
    state:    started
    enabled:  yes