cloudera_director_version:                              6.2.0
cdsw_version:                                           1.5.0
cloudera_director_aws_region:                           eu-west-2
cloudera_director_api_user:                             '{{ director_admin_username }}'
cloudera_director_api_password:                         '{{ director_admin_password }}'
cloudera_director_port:                                 7189
cloudera_director_api_url:                              'https://{{ director_public_dns }}:{{ cloudera_director_port }}/api/v12/environments'
cloudera_director_environment_name:                     dev
cloudera_director_deployment_name:                      '{{ cloudera_director_environment_name }}-deployment'
cloudera_director_create_environment_endpoint:          '{{ cloudera_director_api_url }}'
cloudera_director_create_database_server_endpoint:      '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/databaseServers'
cloudera_director_create_deployment_endpoint:           '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/deployments'
cloudera_director_create_cluster_endpoint:              '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/deployments/{{ cloudera_director_deployment_name }}/clusters'

cloudera_director_terminate_cluster_endpoint:           '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/deployments/{{ cloudera_director_deployment_name }}/clusters/{{ cloudera_director_cluster_name }}'
cloudera_director_terminate_deployment_endpoint:        '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/deployments/{{ cloudera_director_deployment_name }}'
cloudera_director_terminate_environment_endpoint:       '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/'
cloudera_director_terminate_database_server_endpoint:   '{{ cloudera_director_api_url }}/{{ cloudera_director_environment_name }}/databaseServers/{{ aws_properties.cluster_types[cluster_type].deployment.cloudera_database_server_name }}'

cloudera_director_environment_region_name:              '{{ cloudera_director_aws_region }}'
cloudera_director_env_user:                             centos

terraform_tf_state_path:                                '{{ playbook_dir }}/../terraform/aws/terraform.tfstate'

cluster_type:                                           basic

cloudera_director_cluster_name:                         '{{ cloudera_director_environment_name }}-cluster'
cloudera_director_cluster_config_template:              'cluster_{{ cluster_type }}_template.j2'

aws_properties:
  global:
    cloudera_director_sg_id:                            '{{ cloudera_director_sg_id }}'
    cloudera_director_subnet_id:                        '{{ cloudera_director_subnet_id }}'
    cloudera_director_db_subnet_group_name:             '{{ cloudera_director_db_subnet_group_name }}'
  cluster_types:
    basic:
      deployment:
        cloudera_manager_ami_name:                        '{{ cloudera_director_ami }}'
        cloudera_manager_ec2_type:                        m4.large
        cloudera_database_server_name:                    'cloudera-{{ cloudera_director_environment_name }}-db'
        cloudera_database_server_engine:                  MYSQL
        cloudera_database_server_engine_version:          5.6.40
        cloudera_database_server_allocated_storage:       20
        cloudera_database_server_db_instance_class:       db.t2.micro
      cluster:
        masternode:
          cloudera_cluster_template_name:                 'master-node-{{ cloudera_director_environment_name }}'
          cloudera_cluster_ec2_type:                      m4.xlarge
          cloudera_cluster_ami_name:                      '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                  1
        datanode:
          cloudera_cluster_template_name:                 'data-node-{{ cloudera_director_environment_name }}'
          cloudera_cluster_ec2_type:                      m4.xlarge
          cloudera_cluster_ami_name:                      '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                  3
        edgenode:
          cloudera_cluster_template_name:                 'edge-node-{{ cloudera_director_environment_name }}'
          cloudera_cluster_ec2_type:                      m4.large
          cloudera_cluster_ami_name:                      '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                  1
        cdswmasternode:
          cloudera_cluster_template_name:                 'cdsw-master-node-{{ env_name }}'
          cloudera_cluster_ec2_type:                      m4.large
          cloudera_cluster_ami_name:                      '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                  1
        cdswworker:
          cloudera_cluster_template_name:                 'cdsw-worker-node-{{ env_name }}'
          cloudera_cluster_ec2_type:                      m4.large
          cloudera_cluster_ami_name:                      '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                  1
    ha:
      deployment:
        cloudera_manager_ami_name:                      '{{ cloudera_director_ami }}'
        cloudera_manager_ec2_type:                      m4.xlarge
        cloudera_database_server_name:                  'cloudera-{{ env_name }}-db'
        cloudera_database_server_engine:                MYSQL
        cloudera_database_server_engine_version:        5.6.40
        cloudera_database_server_allocated_storage:     20
        cloudera_database_server_db_instance_class:     db.t2.micro
      cluster:
        masternode:
          cloudera_cluster_template_name:               'master-node-1-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                1
        masternode_2:
          cloudera_cluster_template_name:               'master-node-2-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                2
        hdfsmasternode_core:
          cloudera_cluster_template_name:               'hdfs-master-core-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                2
        hdfsmasternode_httpfs:
          cloudera_cluster_template_name:               'hdfs-master-httpfs-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                1
        datanode:
          cloudera_cluster_template_name:               'data-node-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                3
        edgenode:
          cloudera_cluster_template_name:               'edge-node-{{ env_name }}'
          cloudera_cluster_ec2_type:                    m4.xlarge
          cloudera_cluster_ami_name:                    '{{ cloudera_director_ami }}'
          cloudera_cluster_nodes_number:                0
