- name: Install kerberos packages
  package:
    name:   "{{ item }}"
    state:  present
  with_items:
    - krb5-libs
    - krb5-workstation
    - krb5-server

- name: Create Kerberos server configuration
  template:
    src:    krb5.conf.j2
    dest:   /etc/krb5.conf
    owner:  root
    group:  root
    mode:   0644
  vars:
    krb_domain_name:   "{{ director_public_dns }}"

- name: Create Kerberos KDC configuration
  template:
    src:    kdc.conf.j2
    dest:   /var/kerberos/krb5kdc/kdc.conf
    owner:  root
    group:  root
    mode:   0600
  vars:
    krb_domain_name:   "{{ director_public_dns }}"

- name: Create Kerberos ADM ACL configuration
  template:
    src:    kadm5.acl.j2
    dest:   /var/kerberos/krb5kdc/kadm5.acl
    owner:  root
    group:  root
    mode:   0600
  vars:
    krb_domain_name:   "{{ director_public_dns }}"

- name: Check if kdc already configured
  stat: path=/var/kerberos/krb5kdc/principal
  register: kdc_config

- name: Initialise KDC
  shell: kdb5_util create -s -P {{ cloudera_kerberos_password }}
  when: kdc_config.stat.exists == false

- name: Create Kerberos admin user
  shell: kadmin.local -q "addprinc -pw {{ cloudera_kerberos_password }} {{ cloudera_kerberos_user }}"
  register: create_admin

- name: Start Kerberos services
  systemd:
    name:     "{{ item }}"
    state:    started
    enabled:  yes
  with_items:
    - kadmin
    - krb5kdc