---
- name: Create Cloudera Director instance
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - inventory/vars/director.yml
    - inventory/vars/vault.yml
  roles:
    - director.setup
    - director.kerberos
    - director.environment
    - director.database
    - director.deployment